#ifndef MINT2DICT_H
#define MINT2DICT_H

#include <map>
#include <string>
#include <vector>
#include <Mint/PhaseDifferenceCalc.h>
#include <Mint/DalitzEventPattern.h>
#include <Mint/DalitzEventList.h>
#include <Mint/DiskResidentEventList.h>
#include <Mint/NamedParameterBase.h>
#include <Mint/TimeDependentGenerator.h>
#include <Mint/SplineGenerator.h>
#include <Mint/FitAmpSum.h>
#include <Mint/DalitzEvent.h>
#include <Mint/binflipChi2.h>
#include <Mint/Minimiser.h>
#include <Mint/Eff3piSymmetric.h>
#include <Mint/IReturnRealForEvent.h>
#include <Mint/HadronicParameters.h>
#include <Mint/TimeBinning.h>
#include <Mint/BinFlipChi2.h>
#include <Mint/SimulMinimisable.h>
#include <Mint/MinuitParameterSet.h>
#include <Mint/FitParameter.h>
#include <Mint/GaussianConstraintChi2.h>
#include <Mint/XYConstraintChi2.h>
#include <Mint/FlexiFastAmplitudeIntegrator.h>
#include <Mint/DalitzPdfSaveInteg.h>

/*
#include <Mint/DalitzBox.h>
#include <Mint/Model_independent.h>
#include <Mint/PolymorphVector.h>
#include <Mint/polVector.h>
#include <Mint/TLorentzVectorC.h>
#include <Mint/DalitzHistogram.h>
#include <Mint/DalitzSet.h>
#include <Mint/SpinFactors4Body_FsVector.h>
#include <Mint/DalitzEventPtrList.h>
#include <Mint/DalitzPdfNormChecker.h>
#include <Mint/phaseSpaceIntegrals.h>
#include <Mint/SpinFactors4Body_ScalarsAndVectors.h>
#include <Mint/SpinFactors3Body_ForRunningWidth.h>
#include <Mint/FitAmpPairCovariance.h>
#include <Mint/ComplexProductForEvent.h>
#include <Mint/DalitzPdfBaseFastInteg.h>
#include <Mint/Flatte.h>
#include <Mint/DalitzHistoStackSet.h>
#include <Mint/SymmLorentzMatrix.h>
#include <Mint/ParticlePropertiesList.h>
#include <Mint/TGenPhaseSpaceWithRnd.h>
#include <Mint/FlatFct.h>
#include <Mint/NamedParameterStream.h>
#include <Mint/DalitzHistoSet.h>
#include <Mint/BWFct.h>
#include <Mint/Neg2LLSum.h>
#include <Mint/RunningWidthCalculator.h>
#include <Mint/Amplitude.h>
#include <Mint/ParticleProperties.h>
#include <Mint/MappedDalitzBWArea.h>
#include <Mint/DecayTreeItem.h>
#include <Mint/DDTree.h>
#include <Mint/SpinFactors4Body_Tensors.h>
#include <Mint/FermiPS_BW.h>
#include <Mint/MakePreIntegratedAmplitudes.h>
#include <Mint/singleTopHatShape.h>
#include <Mint/BaseGenerator.h>
#include <Mint/DalitzPdfBaseMCInteg.h>
#include <Mint/BW_BW.h>
#include <Mint/FitAmpPairList.h>
#include <Mint/symMultiPolyTerm.h>
#include <Mint/Chi2Box.h>
#include <Mint/Rho0Omega.h>
#include <Mint/DalitzSumPdf.h>
#include <Mint/DiskResidentEventList.h>
#include <Mint/FitAmpPair.h>
#include <Mint/FitComplex.h>
#include <Mint/FitComplexPolar.h>
#include <Mint/FitFraction.h>
#include <Mint/SignalGenerator.h>
#include <Mint/AmpPair.h>
#include <Mint/Permutator.h>
#include <Mint/GounarisSakurai.h>
#include <Mint/ResonancePropertiesList.h>
#include <Mint/IEvtGen.h>
#include <Mint/MintFcnGrad.h>
#include <Mint/BW_BW_DifferentMother.h>
#include <Mint/AmpInitialiser.h>
#include <Mint/DalitzMCIntegrator.h>
#include <Mint/FitAmpListBase.h>
#include <Mint/IntegCalculator.h>
#include <Mint/NamedParameter.h>
#include <Mint/FitFractionList.h>
#include <Mint/Eff4piSymmetric.h>
#include <Mint/CoherenceFactorCalculator.h>
#include <Mint/FastAmplitudeIntegrator.h>
#include <Mint/DalitzPhaseSpaceBox.h>
#include <Mint/Bugg_BW.h>
#include <Mint/AmpRatios.h>
#include <Mint/CoherenceFactorStoreAndEvaluate.h>
#include <Mint/GeneralisedPareto.h>
#include <Mint/DalitzPdfBaseFlexiFastInteg.h>
#include <Mint/BasicComplex.h>
#include <Mint/Phase.h>
#include <Mint/IReturnComplexForEvent.h>
#include <Mint/Histo_BW.h>
#include <Mint/AssociatingDecayTree.h>
#include <Mint/DalitzMCMC.h>
#include <Mint/LASSO.h>
#include <Mint/FitParRef.h>
#include <Mint/Calculate4BodyProps.h>
#include <Mint/RhoOmegaGS.h>
#include <Mint/FitAmpIncoherentSum.h>
#include <Mint/ReturnWeight.h>
#include <Mint/SpinFactor3.h>
#include <Mint/QuarkContent.h>
#include <Mint/MultiQuarkContent.h>
#include <Mint/ISpinFactor.h>
#include <Mint/DalitzCoordinate.h>
#include <Mint/SBW.h>
#include <Mint/SumOfFitAmpLists.h>
#include <Mint/MultiTopHat.h>
#include <Mint/NamedDecayTreeList.h>
#include <Mint/Neg2LLConstraint.h>
#include <Mint/FitParameter.h>
#include <Mint/FitComplexCart.h>
#include <Mint/Minimisable.h>
#include <Mint/MappedDalitzArea.h>
#include <Mint/symPolyTerm.h>
#include <Mint/DalitzArea.h>
#include <Mint/Lass.h>
#include <Mint/NonRes.h>
#include <Mint/CoherenceFactor.h>
#include <Mint/ReturnPhaseSpace.h>
#include <Mint/GaussFct.h>
#include <Mint/DalitzBoxSet_Method2.h>
#include <Mint/Chi2BoxSet.h>
#include <Mint/DalitzBWBox.h>
#include <Mint/FitAmpList.h>
#include <Mint/MintFcn.h>
#include <Mint/FitParDependent.h>
#include <Mint/SpinFactor.h>
#include <Mint/DalitzPdfBase.h>
#include <Mint/ParsedParameterFile.h>
#include <Mint/EventList.h>
#include <Mint/ResonancePropertiesFitRef.h>
#include <Mint/ParsedParameterLine.h>
#include <Mint/FitAmplitude.h>
#include <Mint/ResonanceProperties.h>
#include <Mint/FromFileGenerator.h>
#include <Mint/ComplexProduct.h>
#include <Mint/AssociatedDecayTreeItem.h>
#include <Mint/ZTspin2.h>
#include <Mint/FitAmpPairFitCovariance.h>
#include <Mint/DalitzBWArea.h>
#include <Mint/Minimiser.h>
#include <Mint/LorentzMatrix.h>
#include <Mint/DalitzBWBoxSet.h>
#include <Mint/DalitzBoxSet.h>
#include <Mint/ZTspin1.h>
#include <Mint/IGenFct.h>
#include <Mint/counted_ptr.h>
#include <Mint/IMinimisable.h>
#include <Mint/EventPtrList.h>
#include <Mint/SpinFactorMaker.h>
#include <Mint/PdfBase.h>
#include <Mint/Permutation.h>
#include <Mint/DecayTreeComparisons.h>
#include <Mint/Utils.h>
#include <Mint/IFastAmplitudeIntegrable.h>
#include <Mint/LineshapeMaker.h>
#include <Mint/SpinSumV.h>
#include <Mint/IUnweightedEventGenerator.h>
#include <Mint/IPdf.h>
#include <Mint/SumPdf.h>
#include <Mint/Chi2Binning.h>
#include <Mint/LeviCivita.h>
#include <Mint/IDalitzEvent.h>
#include <Mint/DecayTree.h>
#include <Mint/AllPossibleSij.h>
#include <Mint/SpinSumT.h>
*/
#endif
